-- Dados privados pertencem sempre ao usuário autenticado.
create table if not exists public.apostas (
  id bigint generated by default as identity primary key,
  user_id uuid default auth.uid() references auth.users(id) on delete cascade,
  concurso integer not null check (concurso > 0),
  dezenas integer[] not null check (cardinality(dezenas) = 6),
  created_at timestamptz not null default now()
);

create table if not exists public.meus_jogos (
  id bigint generated by default as identity primary key,
  user_id uuid default auth.uid() references auth.users(id) on delete cascade,
  jogos jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sugestoes_historico (
  id bigint generated by default as identity primary key,
  user_id uuid default auth.uid() references auth.users(id) on delete cascade,
  concurso integer not null check (concurso > 0),
  sugestoes jsonb not null default '[]'::jsonb,
  resultado integer[],
  acertos integer[],
  verificado_em timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.resultados (
  concurso integer primary key,
  data_sorteio date,
  dezenas integer[] not null check (cardinality(dezenas) = 6),
  acumulado boolean not null default false,
  ganhadores integer not null default 0,
  premio_sena numeric not null default 0
);

alter table public.apostas add column if not exists user_id uuid default auth.uid() references auth.users(id) on delete cascade;
alter table public.meus_jogos add column if not exists user_id uuid default auth.uid() references auth.users(id) on delete cascade;
alter table public.sugestoes_historico add column if not exists user_id uuid default auth.uid() references auth.users(id) on delete cascade;
alter table public.apostas alter column user_id set default auth.uid();
alter table public.meus_jogos alter column user_id set default auth.uid();
alter table public.sugestoes_historico alter column user_id set default auth.uid();

create unique index if not exists meus_jogos_user_id_key on public.meus_jogos(user_id) where user_id is not null;
create unique index if not exists sugestoes_user_concurso_key on public.sugestoes_historico(user_id, concurso) where user_id is not null;

alter table public.apostas enable row level security;
alter table public.meus_jogos enable row level security;
alter table public.sugestoes_historico enable row level security;
alter table public.resultados enable row level security;

-- Remove políticas antigas potencialmente permissivas antes de criar as novas.
do $$
declare policy_record record;
begin
  for policy_record in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in ('apostas', 'meus_jogos', 'sugestoes_historico', 'resultados')
  loop
    execute format(
      'drop policy if exists %I on %I.%I',
      policy_record.policyname,
      policy_record.schemaname,
      policy_record.tablename
    );
  end loop;
end $$;

create policy "Usuários gerenciam as próprias apostas"
on public.apostas for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Usuários gerenciam os próprios jogos"
on public.meus_jogos for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Usuários gerenciam as próprias sugestões"
on public.sugestoes_historico for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Resultados são públicos para leitura"
on public.resultados for select to anon, authenticated
using (true);

revoke all on public.apostas, public.meus_jogos, public.sugestoes_historico from anon;
grant select, insert, update, delete on public.apostas, public.meus_jogos, public.sugestoes_historico to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant select on public.resultados to anon, authenticated;
